import type { ReactNode } from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { AppHeader } from "@/components/layout/app-header"
import { AppFooter } from "@/components/layout/app-footer"
import { Toaster } from "@/components/ui/sonner"
import { QueryClientWrapper } from "@/components/providers/query-client-provider"
import { ClientSessionHydrator } from "@/components/providers/client-session-hydrator"
import { loadSession } from "@/lib/auth/load-session"

const fontSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"]
})

const fontMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"]
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
}

export default async function RootLayout({
    children
}: Readonly<{
    children: ReactNode
}>) {
    const session = await loadSession()
    const serializedSession = JSON.stringify(session ?? null).replace(/</g, "\\u003c")

    return (
        <html lang="en">
            <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable, fontMono.variable)}>
                <script
                    dangerouslySetInnerHTML={{
                        __html: `window.__SESSION__ = ${serializedSession};`
                    }}
                />
                <ClientSessionHydrator />
                <QueryClientWrapper>
                    <AppHeader />
                    <main className="min-h-[80vh]">
                        {children}
                    </main>
                    <AppFooter />
                    <Toaster />
                </QueryClientWrapper>
            </body>
        </html>
    )
}

